FROM asia.gcr.io/psyched-spark-243208/terminal
RUN mkdir -p learning_unix/temp/temp2/temp3
RUN touch learning_unix/temp/heaven.txt
RUN touch learning_unix/temp/earth.txt
RUN touch learning_unix/temp/rags
WORKDIR /home/bioinfo/learning_unix/